name: Setup environment
description: |
  Sets up the development environment for this repository.
  
  Notes:
  1. You have to first checkout the repository.
  2. To use the conda environment, you have to set `defaults.run.shell` to `bash -el {0}`. See [this page](https://github.com/marketplace/actions/setup-miniconda#important) for more details.

inputs:
  python-version:
    description: 'Python version'
    required: false
    default: '3.10'

runs:
  using: composite
  steps:
    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: ${{ inputs.python-version }}
        activate-environment: 'sta-${{ inputs.python-version }}'
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: '2.1.3'
    - name: Create .env file
      run: echo "FILESYSTEM_ROOT=$(pwd)" > .env
      shell: bash
    - name: Install code
      run: bash ./scripts/install.sh
      shell: bash
