// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/api/backend/*": {
    params: {
      "*": string;
    };
  };
  "/source/files/download": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/logout": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/profile/:username": {
    params: {
      "username": string;
    };
  };
  "/settings": {
    params: {};
  };
  "/settings/account": {
    params: {};
  };
  "/settings/authentication": {
    params: {};
  };
  "/settings/preferences": {
    params: {};
  };
  "/settings/profile": {
    params: {};
  };
  "/admin/accounts": {
    params: {};
  };
  "/jobs": {
    params: {};
  };
  "/source": {
    params: {};
  };
  "/source/groups": {
    params: {};
  };
  "/source/files": {
    params: {};
  };
  "/source/data": {
    params: {};
  };
  "/source/data/gmesh": {
    params: {};
  };
  "/source/data/pcd": {
    params: {};
  };
  "/source/specs": {
    params: {};
  };
  "/source/specs/pcd": {
    params: {};
  };
  "/label": {
    params: {};
  };
  "/label/groups": {
    params: {};
  };
  "/label/repos": {
    params: {};
  };
  "/label/data": {
    params: {};
  };
  "/label/data/bbox": {
    params: {};
  };
  "/label/data/segmentation": {
    params: {};
  };
  "/label/data/vector": {
    params: {};
  };
  "/label/specs": {
    params: {};
  };
  "/label/specs/objclass": {
    params: {};
  };
  "/label/specs/objclass/selections": {
    params: {};
  };
  "/label/specs/objclass/definitions": {
    params: {};
  };
  "/label/repos/:groupId": {
    params: {
      "groupId": string;
    };
  };
  "/label/repos/:groupId/branches": {
    params: {
      "groupId": string;
    };
  };
  "/label/repos/:groupId/commits": {
    params: {
      "groupId": string;
    };
  };
  "/projects": {
    params: {};
  };
  "/projects/:projectId/:workType": {
    params: {
      "projectId": string;
      "workType": string;
    };
  };
  "/projects/:projectId": {
    params: {
      "projectId": string;
    };
  };
  "/projects/:projectId/tasks": {
    params: {
      "projectId": string;
    };
  };
  "/projects/:projectId/tasks/:taskId": {
    params: {
      "projectId": string;
      "taskId": string;
    };
  };
  "/projects/:projectId/tasks/:taskId/recent/:workType?": {
    params: {
      "projectId": string;
      "taskId": string;
      "workType"?: string;
    };
  };
  "/projects/:projectId/tasks/:taskId/frames/:workType?": {
    params: {
      "projectId": string;
      "taskId": string;
      "workType"?: string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/api/backend/*" | "/source/files/download" | "/login" | "/logout" | "/profile" | "/profile/:username" | "/settings" | "/settings/account" | "/settings/authentication" | "/settings/preferences" | "/settings/profile" | "/admin/accounts" | "/jobs" | "/source" | "/source/groups" | "/source/files" | "/source/data" | "/source/data/gmesh" | "/source/data/pcd" | "/source/specs" | "/source/specs/pcd" | "/label" | "/label/groups" | "/label/repos" | "/label/data" | "/label/data/bbox" | "/label/data/segmentation" | "/label/data/vector" | "/label/specs" | "/label/specs/objclass" | "/label/specs/objclass/selections" | "/label/specs/objclass/definitions" | "/label/repos/:groupId" | "/label/repos/:groupId/branches" | "/label/repos/:groupId/commits" | "/projects" | "/projects/:projectId/:workType" | "/projects/:projectId" | "/projects/:projectId/tasks" | "/projects/:projectId/tasks/:taskId" | "/projects/:projectId/tasks/:taskId/recent/:workType?" | "/projects/:projectId/tasks/:taskId/frames/:workType?";
  };
  "./routes/backend-proxy.ts": {
    id: "routes/backend-proxy";
    page: "/api/backend/*";
  };
  "./routes/source/files-download.ts": {
    id: "routes/source/files-download";
    page: "/source/files/download";
  };
  "./layouts/public.tsx": {
    id: "layouts/public";
    page: "/login";
  };
  "./routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "./layouts/protected.tsx": {
    id: "layouts/protected";
    page: "/" | "/logout" | "/profile" | "/profile/:username" | "/settings" | "/settings/account" | "/settings/authentication" | "/settings/preferences" | "/settings/profile" | "/admin/accounts" | "/jobs" | "/source" | "/source/groups" | "/source/files" | "/source/data" | "/source/data/gmesh" | "/source/data/pcd" | "/source/specs" | "/source/specs/pcd" | "/label" | "/label/groups" | "/label/repos" | "/label/data" | "/label/data/bbox" | "/label/data/segmentation" | "/label/data/vector" | "/label/specs" | "/label/specs/objclass" | "/label/specs/objclass/selections" | "/label/specs/objclass/definitions" | "/label/repos/:groupId" | "/label/repos/:groupId/branches" | "/label/repos/:groupId/commits" | "/projects" | "/projects/:projectId/:workType" | "/projects/:projectId" | "/projects/:projectId/tasks" | "/projects/:projectId/tasks/:taskId" | "/projects/:projectId/tasks/:taskId/recent/:workType?" | "/projects/:projectId/tasks/:taskId/frames/:workType?";
  };
  "./routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/";
  };
  "./routes/logout.tsx": {
    id: "routes/logout";
    page: "/logout";
  };
  "./routes/profile.tsx": {
    id: "routes/profile-self";
    page: "/profile";
  } | {
    id: "routes/profile-user";
    page: "/profile/:username";
  };
  "./routes/settings/index.ts": {
    id: "routes/settings/index";
    page: "/settings";
  };
  "./routes/settings/account.tsx": {
    id: "routes/settings/account";
    page: "/settings/account";
  };
  "./routes/settings/authentication.tsx": {
    id: "routes/settings/authentication";
    page: "/settings/authentication";
  };
  "./routes/settings/preferences.tsx": {
    id: "routes/settings/preferences";
    page: "/settings/preferences";
  };
  "./routes/settings/profile.tsx": {
    id: "routes/settings/profile";
    page: "/settings/profile";
  };
  "./routes/admin/accounts.tsx": {
    id: "routes/admin/accounts";
    page: "/admin/accounts";
  };
  "./routes/jobs.tsx": {
    id: "routes/jobs";
    page: "/jobs";
  };
  "./layouts/source.tsx": {
    id: "layouts/source";
    page: "/source" | "/source/groups" | "/source/files" | "/source/data" | "/source/data/gmesh" | "/source/data/pcd" | "/source/specs" | "/source/specs/pcd";
  };
  "./routes/source/index.ts": {
    id: "routes/source/index";
    page: "/source";
  };
  "./routes/source/groups.tsx": {
    id: "routes/source/groups";
    page: "/source/groups";
  };
  "./routes/source/files.tsx": {
    id: "routes/source/files";
    page: "/source/files";
  };
  "./routes/source/data/dashboard.tsx": {
    id: "routes/source/data/dashboard";
    page: "/source/data";
  };
  "../../../plugins/gmesh/frontend/app/source/data/metadata.tsx": {
    id: "/home/cyrusleung/st-annotator/plugins/gmesh/frontend/app/source/data/metadata";
    page: "/source/data/gmesh";
  };
  "../../../plugins/pcd/frontend/app/source/data/metadata.tsx": {
    id: "/home/cyrusleung/st-annotator/plugins/pcd/frontend/app/source/data/metadata";
    page: "/source/data/pcd";
  };
  "./routes/source/specs/dashboard.tsx": {
    id: "routes/source/specs/dashboard";
    page: "/source/specs";
  };
  "../../../plugins/pcd/frontend/app/source/specs/specs.tsx": {
    id: "/home/cyrusleung/st-annotator/plugins/pcd/frontend/app/source/specs/specs";
    page: "/source/specs/pcd";
  };
  "./layouts/label.tsx": {
    id: "layouts/label";
    page: "/label" | "/label/groups" | "/label/repos" | "/label/data" | "/label/data/bbox" | "/label/data/segmentation" | "/label/data/vector" | "/label/specs" | "/label/specs/objclass" | "/label/specs/objclass/selections" | "/label/specs/objclass/definitions";
  };
  "./routes/label/index.ts": {
    id: "routes/label/index";
    page: "/label";
  };
  "./routes/label/groups.tsx": {
    id: "routes/label/groups";
    page: "/label/groups";
  };
  "./routes/label/repos.tsx": {
    id: "routes/label/repos";
    page: "/label/repos";
  };
  "./routes/label/data/dashboard.tsx": {
    id: "routes/label/data/dashboard";
    page: "/label/data";
  };
  "../../../plugins/bbox/frontend/app/label/data/bbox.tsx": {
    id: "/home/cyrusleung/st-annotator/plugins/bbox/frontend/app/label/data/bbox";
    page: "/label/data/bbox";
  };
  "../../../plugins/segmentation/frontend/app/label/data/segmentation.tsx": {
    id: "/home/cyrusleung/st-annotator/plugins/segmentation/frontend/app/label/data/segmentation";
    page: "/label/data/segmentation";
  };
  "../../../plugins/vector/frontend/app/label/data/vector.tsx": {
    id: "/home/cyrusleung/st-annotator/plugins/vector/frontend/app/label/data/vector";
    page: "/label/data/vector";
  };
  "./routes/label/specs/dashboard.tsx": {
    id: "routes/label/specs/dashboard";
    page: "/label/specs";
  };
  "./routes/label/specs/objclass/index.ts": {
    id: "routes/label/specs/objclass/index";
    page: "/label/specs/objclass";
  };
  "./routes/label/specs/objclass/selections.tsx": {
    id: "routes/label/specs/objclass/selections";
    page: "/label/specs/objclass/selections";
  };
  "./routes/label/specs/objclass/definitions.tsx": {
    id: "routes/label/specs/objclass/definitions";
    page: "/label/specs/objclass/definitions";
  };
  "./layouts/repo.tsx": {
    id: "layouts/repo";
    page: "/label/repos/:groupId" | "/label/repos/:groupId/branches" | "/label/repos/:groupId/commits";
  };
  "./routes/label/repo/index.ts": {
    id: "routes/label/repo/index";
    page: "/label/repos/:groupId";
  };
  "./routes/label/repo/branches.tsx": {
    id: "routes/label/repo/branches";
    page: "/label/repos/:groupId/branches";
  };
  "./routes/label/repo/commits.tsx": {
    id: "routes/label/repo/commits";
    page: "/label/repos/:groupId/commits";
  };
  "./routes/projects.tsx": {
    id: "routes/projects";
    page: "/projects";
  };
  "./routes/editor/editor.tsx": {
    id: "routes/editor/editor";
    page: "/projects/:projectId/:workType";
  };
  "./layouts/project.tsx": {
    id: "layouts/project";
    page: "/projects/:projectId" | "/projects/:projectId/tasks";
  };
  "./routes/project/index.ts": {
    id: "routes/project/index";
    page: "/projects/:projectId";
  };
  "./routes/project/tasks.tsx": {
    id: "routes/project/tasks";
    page: "/projects/:projectId/tasks";
  };
  "./layouts/task.tsx": {
    id: "layouts/task";
    page: "/projects/:projectId/tasks/:taskId" | "/projects/:projectId/tasks/:taskId/recent/:workType?" | "/projects/:projectId/tasks/:taskId/frames/:workType?";
  };
  "./routes/project/task/index.ts": {
    id: "routes/project/task/index";
    page: "/projects/:projectId/tasks/:taskId";
  };
  "./routes/project/task/recent.tsx": {
    id: "routes/project/task/recent";
    page: "/projects/:projectId/tasks/:taskId/recent/:workType?";
  };
  "./routes/project/task/frames.tsx": {
    id: "routes/project/task/frames";
    page: "/projects/:projectId/tasks/:taskId/frames/:workType?";
  };
};