from typing import Any, ClassVar

from sqlalchemy.sql.sqltypes import String
from sqlmodel import Field, Relationship, SQLModel

from sta.common.database.types import JSONB
from sta.common.utils.json import JSONType
from sta.models.base import sqlmodel_sa_type

from .base import (
    OptimisticLockingSQLModel,
    OptimisticLockingUpdate,
    non_nullable_field_names,
)
from .user import User, Username


class _AccountBase(OptimisticLockingSQLModel):
    username: Username = Field(sa_type=sqlmodel_sa_type(String(31)), nullable=False, unique=True)
    # Preferences may be cleared; persist that state as SQL NULL.
    preferences: JSONType | None = Field(sa_type=JSONB, nullable=True, default=None)


class Account(_AccountBase, table=True):
    __tablename__: ClassVar[Any] = "account"

    id: int = Field(
        foreign_key="user.id",
        ondelete="CASCADE",
        primary_key=True,
        nullable=False,
    )
    user: User = Relationship()


class AccountCreate(_AccountBase):
    # Account mirrors User 1:1, so the primary key is not autogenerated:
    # the caller must provide the id of the backing User.
    id: int


class AccountPublic(_AccountBase):
    id: int

    def __hash__(self) -> int:
        return hash(self.id)


class AccountPublicSummary(SQLModel):
    """
    The shape of an account that other users may see.

    Adding a field here is a disclosure decision: positions where the reader is
    not the account owner are typed as this model, which is why it does not
    extend :class:`_AccountBase`.
    """

    id: int
    username: Username

    def __hash__(self) -> int:
        return hash(self.id)


class AccountUpdate(OptimisticLockingUpdate):
    _null_forbidden_fields: ClassVar[frozenset[str]] = non_nullable_field_names(_AccountBase)

    username: Username | None = None
    preferences: JSONType | None = None


class AccountBulkUpdate(SQLModel):
    preferences: JSONType | None = None
