[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[project]
name = "sta-vector"
version = "5.0.0"
description = "ST Annotator Vector Labels Plugin"
license = "Apache-2.0"
requires-python = ">=3.10"
authors = [
    { name = "Cyrus Leung", email = "tlleungac@connect.ust.hk"},
    { name = "Maral Bahari", email = "mbahari@connect.ust.hk"},
]
keywords = [
    "computer-vision",
    "3d", "spatiotemporal", "spatio-temporal", "spatial-temporal",
    "polygon", "polyline", "point",
    "annotation", "annotation-tool",
    "labeling", "labeling-tool",
]

[project.urls]
homepage = "https://github.com/DESRLab/st-annotator"
repository = "https://github.com/DESRLab/st-annotator"

[project.entry-points."sta.plugins"]
registry = "sta_vector.plugin:register"

[tool.poetry.dependencies]
python = ">=3.10,<4.0"

sta = { path = "../../../backend", develop = true }
sta-pcd = { path = "../../pcd/backend", develop = true }

pydantic = "^2.6"
pydantic_core = "^2.46"
pytz = ">=2023.3"
typing-extensions = ">=4.6"
uuid6 = ">=2024.1"

shapely = ">=2.0"

fastapi = {extras = ["standard"], version = "^0.115.13"}
sqlmodel = "^0.0.24"
SQLAlchemy = "^2.0"
geoalchemy2 = "^0.15.2"

click = ">=8.1"
tqdm = ">=4.23"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
deptry = ">=0.14"
ruff = ">=0.3"
pyright = ">=1.1.354"

pytest = ">=7.0"
pytest-cov = ">=3.0"
pytest-xdist = ">=3.5"

[tool.deptry]
extend_exclude = ["\\.coverage/", "test", "__pycache__", "node_modules"]

[tool.deptry.per_rule_ignores]
DEP001 = ["_typeshed"]

[tool.ruff]
extend = "../../../config/python/pyproject.toml"

[tool.pytest.ini_options]
addopts = "--cov=sta_vector --cov-report=term-missing --cov-report html:coverage --cov-branch --cov-context=test"
testpaths = ["test"]

[tool.coverage.html]
show_contexts = true

[tool.coverage.report]
exclude_also = [
    "def __repr__",
    "if self.debug:",
    "if settings.DEBUG",
    "raise AssertionError",
    "raise NotImplementedError",
    "if 0:",
    "if __name__ == .__main__.:",
    "if TYPE_CHECKING:",
    "class .*\\bProtocol(\\[.*\\])?\\):",
    "@(abc\\.)?abstractmethod",
    "@(typing\\.)?overload",
]
