import type { JSX, ReactNode } from "react";

interface TweakpaneRackProps {
  children: ReactNode;
  className?: string;
}

interface TweakpaneSeparatorProps {
  paddingTop?: string | null;
}

/**
 * Provides the same root/content structure and spacing variables as a titleless Tweakpane Pane.
 *
 */
export function TweakpaneRack({
  children,
  className = "",
}: TweakpaneRackProps): JSX.Element {
  return (
    <div className={"tp-rotv tp-rotv-expanded tp-rotv-not " + className}>
      <div className="tp-rotv_c" style={{ height: "auto" }}>
        {children}
      </div>
    </div>
  );
}

/**
 * Matches the separator blade generated by Tweakpane.
 *
 */
export function TweakpaneSeparator({
  paddingTop = null,
}: TweakpaneSeparatorProps): JSX.Element {
  return (
    <div
      className="tp-sprv"
      style={paddingTop == null ? undefined : { paddingTop }}
    >
      <hr className="tp-sprv_r" />
    </div>
  );
}
