name: Publish documentation

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  contents: read

defaults:
  run:
    shell: bash -el {0}

concurrency:
  group: github-pages-deployment
  cancel-in-progress: true

jobs:
  docs:
    name: Build documentation
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    services:
      postgis:
        image: postgis/postgis:16-3.4
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: sta
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/actions/setup
      - name: Generate documentation
        run: bash ./scripts/doc.sh
      - name: Upload documentation artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: site

  deploy:
    name: Publish documentation
    needs: docs
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy documentation to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
